language: cpp

env:
  - secure: "y81XpWA0pgw18ZszT93q/1RRhsOdYfgVNAfntrNNQHxb4bFmUgxNdumxDWJrW3M4JvZLLlSQtaiszB1Q5gIHYd9dBXMmn9fs7r0X924ivLUt9gtRcPuYISBphYMda1mkZtum3BRSMPZthy7h9QCaIIZEoLzwBezg3XlKb+LaUfs="

before_install:
  -  APMDIR=$(pwd) && pushd .. && $APMDIR/Tools/scripts/install-travis-env.sh -y && . ~/.profile && popd

script: 
  - Tools/scripts/build_all_travis.sh

deploy:
  provider: releases
  api-key: ${GITHUB_API_KEY}
  file:
  - "ArduCopter/ArduCopter-v2.px4"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
